Map stocksNames = {
  'B3SA3': 'Brasil Bolsa Balcão',
  'BBDC4': 'Banco Bradesco SA Preference Shares',
  'RADL3': 'Raia Drogasil SA',
  'SUZB3': 'Suzano SA',
  'BRFS3': 'Perdigão',
  'VALE3': 'Vale S.A.',
  'MRFG3': 'Marfrig',
  'PETR4': 'Petroleo Brasileiro SA Petrobras Preference Shares',
  'GOLL4': 'Gol Linhas Aéreas',
  'KROT3': 'kroton',
  'ABEV3': 'AMBEV',
  'CIEL3': 'Cielo',
  'IRBR3': 'IRB Brasil RE',
  'BBSE3': 'BB Seguridade',
  'BRDT3': 'Petrobras Distribuidora',
  'CVCB3': 'CVC BRASIL OPERADORA E AGÊNCIA DE VIAGENS S.A.',
  'CCRO3': 'Grupo CCR',
  'GGBR4': 'Gerdau',
  'AZUL4': 'Azul SA',
  'GOAU4': 'Metalurgica Gerdau S.A. Preference Shares',
  'ELET3': 'Centrais Eletricas Brasileiras SA',
  'BTOW3': 'B2W Digital',
  'BBAS3': 'Banco do Brasil SA',
  'CSNA3': 'Companhia Siderúrgica Nacional',
  'PETR3': 'Petroleo Brasileiro SA Petrobras',
  'ELET6': 'Centrais Eletricas Brasileiras SA Preference Shares Series B',
  'ITSA4': 'Itausa Investimentos Itau SA Preference Shares',
  'PCAR4': 'Pão de açucar',
  'SBSP3': 'Companhia de Saneamento Básico do Estado de São Paulo',
  'NATU3': 'Natura',
  'CMIG4': 'Companhia Energetica de Minas Gerais CEMIG',
  'ITUB4': 'Itaú Unibanco',
  'LREN3': 'Lojas Renner',
  'GNDI3': 'Notre Dame Intermedica Participacoes SA',
  'VVAR3': 'Via Varejo',
  'MGLU3': 'Magazine Luiza',
  'RAIL3': 'Rumo SA',
  'UGPA3': 'Grupo Ultra',
  'RENT3': 'Localiza Hertz',
  'JBSS3': 'JBS',
};
